### ISSUE TITLE
Issue with #791: Missing data allowed when training, but not inferencing

### ISSUE THREAD

**Issue by esbraun** [py-why/EconML#827]
#791 ought to allow missing data when inferencing if allow_missing = True, but currently an error is thrown when the inference data includes missing data. RE: below for a working example based on the "Metalearner Examples" notebook for a demonstration of the issue.

https://colab.research.google.com/drive/1QT-IdwRWRUiQNDwqJ0EXPXSftDuIg3uE?usp=sharing

**Comment by Ftrejo23** [comment]
I'm seeing the same issue

**Comment by fverac** [comment]
Thanks for raising this issue. In the original PR we originally only considered missing data during training, but it seems there is interest in extending this to inferencing as well.

**Comment by erasedcitizen11** [comment]
Hi there, just wondering if there any update on this as running into the same problems (doesn't allow missing values when computing CATE/ATE).

**Comment by esbraun** [comment]
@erasedcitizen11 I created a fork that disables the missing value checks which is a requirement for our use cases. Use at your own risk: https://github.com/esbraun/EconML/tree/main

**Comment by pgeertsema** [comment]
@EconML team. Great product!

Any progress in remediating this issue? It appears that scikit-learn's default input validation checks remain in place even when ```allow_missing=True``` is set in DML() and the base learners support missing values (such as LightGBM). This is inconsistent with the documentation (at https://econml.azurewebsites.net/_autosummary/econml.dml.DML.html, see allow_missing (bool)). A self-contained minimal working example follows: 

```
import numpy as np
import scipy.special as sc
from econml.dml import DML
from econml.sklearn_extensions.linear_model import StatsModelsLinearRegression
from lightgbm import LGBMRegressor, LGBMClassifier

np.random.seed(123)
X = np.random.normal(size=(1000, 5))
T = np.random.binomial(1, sc.expit(X[:, 0]))

mask = np.random.rand(*X.shape) < 0.05
X[mask] = np.nan

y = (1 + .5*X[:, 0]) * T + X[:, 0] + np.random.normal(size=(1000,))
est = DML(
    # both base learner models support missing values out of the box
    model_y=LGBMRegressor(),
    model_t=LGBMClassifier(),
    model_final=StatsModelsLinearRegression(fit_intercept=False),
    # should allow discrete treatment
    discrete_treatment=True,
    allow_missing=True,
)
est.fit(y, T, X=X, W=None)

```

It terminates with

```
Traceback (most recent call last):
  File "c:\Users\Paul\Dropbox\DML\MLcode\another test.py", line 24, in <module>
    est.fit(y, T, X=X, W=None)
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\dml\dml.py", line 589, in fit
    return super().fit(Y, T, X=X, W=W, sample_weight=sample_weight, freq_weight=freq_weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\dml\_rlearner.py", line 415, in fit
    return super().fit(Y, T, X=X, W=W,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\_cate_estimator.py", line 131, in call
    m(self, Y, T, *args, **kwargs)
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\_ortho_learner.py", line 745, in fit
    Y, T, Z, sample_weight, freq_weight, sample_var, groups = check_input_arrays(
                                                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\utilities.py", line 578, in check_input_arrays
    new_arg = check_array(arg, dtype=dtype, ensure_2d=False, accept_sparse=True,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\sklearn\utils\validation.py", line 1064, in check_array
    _assert_all_finite(
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\sklearn\utils\validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\sklearn\utils\validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

```
@esbraun: Thanks for the workaround; this is helpful. In the longer term it would be better if we could remediate the issue in the main branch.

**Comment by kbattocchi** [comment]
@pgeertsema we allow missing values in W and X, but your DGP also produces missing values in Y, which we never allow.  You can just filter those rows out if you want to fit on the remaining data.

**Comment by pgeertsema** [comment]
@kbattocchi Yes, of course if there are missing values in Y, then I can see why it would not work. As noted by @esbraun, the issue is that the second stage (inference) fails *even if there are no missing values in Y.*

The code snippet below has no missing values in Y and base models that can handle missing values in X, but still fails:

```
import numpy as np
import scipy.special as sc
from econml.dml import DML
from econml.sklearn_extensions.linear_model import StatsModelsLinearRegression
from lightgbm import LGBMRegressor, LGBMClassifier

np.random.seed(123)
X = np.random.normal(size=(1000, 5))
T = np.random.binomial(1, sc.expit(X[:, 0]))

# mo missing values in Y
y = (1 + .5*X[:, 0]) * T + X[:, 0] + np.random.normal(size=(1000,))

# missing values in X only
mask = np.random.rand(*X.shape) < 0.05
X[mask] = np.nan

est = DML(
    # both base learner models support missing values out of the box
    model_y=LGBMRegressor(),
    model_t=LGBMClassifier(),
    model_final=StatsModelsLinearRegression(fit_intercept=False),
    # should allow discrete treatment
    discrete_treatment=True,
    allow_missing=True,
)
est.fit(y, T, X=X, W=None)
```

Running the above yields:

```
Traceback (most recent call last):
  File "c:\Users\Paul\Dropbox\DML\MLcode\EconML error.py", line 27, in <module>
    est.fit(y, T, X=X, W=None)
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\dml\dml.py", line 589, in fit
    return super().fit(Y, T, X=X, W=W, sample_weight=sample_weight, freq_weight=freq_weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\dml\_rlearner.py", line 415, in fit
    return super().fit(Y, T, X=X, W=W,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\_cate_estimator.py", line 131, in call
    m(self, Y, T, *args, **kwargs)
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\_ortho_learner.py", line 877, in fit
    self._fit_final(Y=Y,
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\_ortho_learner.py", line 980, in _fit_final
    self._ortho_learner_model_final.fit(Y, T, **filter_none_kwargs(X=X, W=W, Z=Z,
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\dml\_rlearner.py", line 94, in fit
    self._model_final.fit(X, T, T_res, Y_res, sample_weight=sample_weight,
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\dml\dml.py", line 163, in fit
    self._model.fit(fts, Y_res, **filtered_kwargs)
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\sklearn_extensions\linear_model.py", line 1794, in fit  
    X, y, freq_weight, sample_var = self._check_input(X, y, sample_weight, freq_weight, sample_var)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\sklearn_extensions\linear_model.py", line 1706, in _check_input
    X, y, sample_weight, freq_weight, sample_var = check_input_arrays(
                                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\econml\utilities.py", line 578, in check_input_arrays
    new_arg = check_array(arg, dtype=dtype, ensure_2d=False, accept_sparse=True,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\sklearn\utils\validation.py", line 1064, in check_array        
    _assert_all_finite(
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\sklearn\utils\validation.py", line 123, in _assert_all_finite  
    _assert_all_finite_element_wise(
  File "C:\Users\Paul\anaconda3\envs\dml\Lib\site-packages\sklearn\utils\validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
```
Sorry for the earlier confusion; hopefully this makes clear where we see the inconsistency with the documentation.

**Comment by fburgaud** [comment]
@fverac Have you tried this for inference though? I've used final models that accept nulls, but the inference step failed because there is a table check step at the beginning that errors out the process before it even tries to use the models.

**Comment by fburgaud** [comment]
Can it reuse the same X preprocessor as the model at least? So that if null values were already dealt with in that way, they can use it again (which would then also be consistent with the features directly used by the models).
Or allowing a specific preprocessor for the trees would be good too...
Right now I just don't have any manual fix I can apply if anything was trained with null values.

**Comment by fverac** [comment]
I don't think we can reuse the same preprocessor as the model_final. Consider models that natively handle missing values, like LGBMRegressor. I don't see how we borrow what the model does.

A simple solution would be to fill the missing values before you call the treeinterpreter, but again this doesn't necessarily work cleanly if you have a model_final that handles missing values natively, and is expecting missing values for the const_marginal_effect call. 

Another solution that could work is introducing an ability to pass a featurizer (e.g. missing value handler) to the Tree Interpreter models specifically. But I'm not sure if this will cause confusion with the column names on display in the visualization, if for example the featurizer adds new columns and manipulates existing ones to address the missing values. 

I'm inclined to consider this out of scope for my current PR which is ready to merge and implement a solution for tree interpreters (like my last one above) another time.

**Comment by fburgaud** [comment]
Fair enough. I'll open a new issue with a more suitable scope.
