### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by ronikobrosly** [py-why/EconML#913]
Hi, I'm working on a PR but first I'd like to make sure I can get all tests running. I followed all of the instructions in the [For Developers, Pre-commit hooks, and Running the tests section of the README](https://github.com/py-why/EconML?tab=readme-ov-file#for-developers). When I run the command `python setup.py pytest` I get the following:

```
(econml) C:\Users\ronik\Desktop\EconML>python setup.py pytest
C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\ptr\__init__.py:81: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
!!

        ********************************************************************************
        Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

        By 2024-Nov-15, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.
        ********************************************************************************

!!
  class PyTest(orig.test):
running pytest
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    setup(ext_modules=c_extensions + pyx_extensions,
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\setuptools\__init__.py", line 111, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\setuptools\_distutils\dist.py", line 964, in run_commands
    self.run_command(cmd)
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\setuptools\dist.py", line 948, in run_command
    super().run_command(command)
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\setuptools\_distutils\dist.py", line 983, in run_command
    cmd_obj.run()
  File "C:\Users\ronik\anaconda3\envs\econml\lib\site-packages\ptr\__init__.py", line 195, in run
    setattr(dist, attr, getattr(self.distribution, attr))
AttributeError: 'Distribution' object has no attribute 'tests_require'
```

This is with python 3.8.x. Any suggestions?

**Comment by ronikobrosly** [comment]
Okay thanks for the heads up @kbattocchi !
